# -*- coding: utf-8 -*-
"""Tarea 1.3 - Métodos numéricos y probabilidades .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H4b0GMo-HhV2rka_SsjeeHK28dfCEGnr

#Tarea 1.3
Mahina Montoya Zavala |
Métodos numéricos y probabilidades

Corrija el siguiente código
"""

def fun(n):
    return x

print(fun(1))

#Como explica el error, x no está definido y es esto lo se debe corregir. 
def fun(n):
  x = n+1 #se ha definido x, dentro de este bloque de código, en base a n para que esta variable sea utilizada. La definiciín de x es una función arbitraria.
  return x

print(fun(1))